import React from 'react';
import PrintLayout from './PrintLayout';

interface ReportPrintTemplateProps {
  report: {
    title: string;
    branchName: string;
    dateRange: string;
    data: any[];
    summary?: any;
  };
  companySettings: {
    companyName: string;
    tinNumber: string;
    address: string;
    phone: string;
    email: string;
    logo?: string;
  };
}

const ReportPrintTemplate: React.FC<ReportPrintTemplateProps> = ({ report, companySettings }) => (
  <PrintLayout title={report.title}>
    <div style={{ textAlign: 'center', marginBottom: 24 }}>
      {companySettings.logo && <img src={companySettings.logo} alt="Logo" style={{ width: 80, height: 60, marginBottom: 8 }} />}
      <div style={{ fontWeight: 'bold', fontSize: 22 }}>{companySettings.companyName}</div>
      <div style={{ fontSize: 12, color: '#555' }}>TIN: {companySettings.tinNumber}</div>
      <div style={{ fontSize: 12, color: '#555' }}>{companySettings.address}</div>
      <div style={{ fontSize: 12, color: '#555' }}>Branch: {report.branchName}</div>
      <div style={{ fontSize: 12, color: '#555' }}>Tel: {companySettings.phone} | Email: {companySettings.email}</div>
    </div>
    <div style={{ marginBottom: 12 }}>
      <div><b>Date Range:</b> {report.dateRange}</div>
    </div>
    {report.summary && (
      <div style={{ marginBottom: 16 }}>
        <b>Summary:</b>
        <ul style={{ margin: 0, padding: 0, listStyle: 'none' }}>
          {Object.entries(report.summary).map(([key, value]) => (
            <li key={key}>{key}: {value}</li>
          ))}
        </ul>
      </div>
    )}
    <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: 16 }}>
      <thead>
        <tr style={{ borderBottom: '2px solid #222' }}>
          {report.data && report.data.length > 0 && Object.keys(report.data[0]).map((header, idx) => (
            <th key={idx} style={{ textAlign: 'left', padding: 8 }}>{header}</th>
          ))}
        </tr>
      </thead>
      <tbody>
        {report.data && report.data.length > 0 ? report.data.map((row, idx) => (
          <tr key={idx} style={{ borderBottom: '1px solid #eee' }}>
            {Object.values(row).map((val, i) => (
              <td key={i} style={{ padding: 8 }}>{val}</td>
            ))}
          </tr>
        )) : (
          <tr>
            <td colSpan={report.data && report.data.length > 0 ? Object.keys(report.data[0]).length : 1} style={{ textAlign: 'center', padding: 16 }}>No data</td>
          </tr>
        )}
      </tbody>
    </table>
    <div style={{ marginTop: 32, textAlign: 'center', fontSize: 13, borderTop: '1px solid #222', paddingTop: 16 }}>
      <div style={{ fontWeight: 'bold' }}>Generated by PMS System</div>
      <div style={{ marginTop: 4 }}>For inquiries, contact us at {companySettings.phone}</div>
    </div>
  </PrintLayout>
);

export default ReportPrintTemplate;
